port: 443
directory: ~/.dathttpd
letsencrypt:
  email: 'bob@foo.com'
  aggreeTos: true
sites:
  datprotocol.myhostname.com:
    url: dat://ff34725120b2f3c5bd5028e4f61d14a45a22af48a7b12126d5d588becde88a93/
    datOnly: false
  portal.myhostname.com:
    url: dat://1f968afe867f06b0d344c11efc23591c7f8c5fb3b4ac938d6000f330f6ee2a03/
    datOnly: true